name: "XMTP Terraform Deployer"
description: "Update a Terraform variable and then create/apply a new run"
branding:
  icon: x
  color: purple
inputs:
  terraform-token:
    description: "Terraform cloud token"
    required: true
  terraform-org:
    description: "Terraform organization that contains the specified workspace"
    required: true
  terraform-workspace:
    description: "Terraform Workspace to update and apply into"
    required: true
  variable-name:
    description: >
      One or more Terraform variable names to update (comma-separated).
      Must match the number and order of entries in variable-value.
    required: true
  variable-value:
    description: >
      One or more values to set for each variable (comma-separated, same order as variable-name).
    required: true
  variable-value-required-prefix:
    description: "Require the value specified in `variable-value` to have the supplied prefix"
  run-title-override:
    description: "The title of the terraform run. If not specified, defaults to latest commit message"
  timeout:
    description: "The timeout for the terraform run. If not specified, defaults to 15 minutes"
    default: "15m"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    TERRAFORM_TOKEN: ${{ inputs.terraform-token }}
    TERRAFORM_ORGANIZATION: ${{ inputs.terraform-org }}
    TERRAFORM_WORKSPACE: ${{ inputs.terraform-workspace }}
    TERRAFORM_VARIABLE_NAME: ${{ inputs.variable-name }}
    TERRAFORM_VARIABLE_VALUE: ${{ inputs.variable-value }}
    VARIABLE_VALUE_REQUIRED_PREFIX: ${{ inputs.variable-value-required-prefix }}
    TERRAFORM_RUN_TITLE: ${{ inputs.run-title-override }}
    TIMEOUT: ${{ inputs.timeout }}
